---
abstract: 'A simple application layer to divide and integrate data and processes in the Perl program.'
author:
  - 'lottz <lottzaddr@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Su
provides:
  Su:
    file: lib/Su.pm
    version: 0.110
  Su::Log:
    file: lib/Su/Log.pm
    version: 0
  Su::Model:
    file: lib/Su/Model.pm
    version: 0
  Su::Process:
    file: lib/Su/Process.pm
    version: 0
  Su::Procs::ResourceProc:
    file: lib/Su/Procs/ResourceProc.pm
    version: 0
  Su::Template:
    file: lib/Su/Template.pm
    version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.110
